### PR TITLE
Assets unloading to free up VRAM

### LINKED ISSUE #15: The web app doesn’t appear to unload GLBs
The web app doesn’t appear to unload GLBs that have been previewed from memory. I managed to create an 8GB Chrome tab which is absurd. This can crash tabs on low spec devices.

Image

### PR DESCRIPTION
**Pull request by Maksims**
Fixes https://github.com/msquared-io/avatar-creator/issues/15

This PR implements a cache of assets as well as ability to unload assets when they are not in use and have been not in use certain amount of time (1 second atm).
There is also a debug panel for stats, enabled by `assetLoader.debugAssets`.

### CODE REVIEW

File: packages/avatar-creator/src/scripts/avatar-loader.ts [hunk 1]
```diff
@@ -607,4 +633,63 @@ export class AvatarLoader extends EventHandler {
...
+
+    const url: string = this.urlByAsset.get(asset) as string;
+    this.assetsCacheByUrl.delete(url);
+
+    this.urlByAsset.delete(asset);
+
+    this.updateStats();
+  }
+
+  update() {
```
Comment (DomGeoT) [inline packages/avatar-creator/src/scripts/avatar-loader.ts:671]: is there a more descriptive name we can use for this
e.g. `checkAssetsCache` or similar - `update` does not help say what is going on here

**Review by DomGeoT — APPROVED** [review]
